INSERT INTO catalog(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
    VALUES('CATALOG-001', 'Berlin', 100, 1500);
INSERT INTO catalog(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
    VALUES('CATALOG-002', 'Tokyo', 110, 1000);
INSERT INTO catalog(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
    VALUES('CATALOG-003', 'Stockholm', 120, 2000);